<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <?php
        echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/reset.css')
                ->prependStylesheet($this->basePath() . '/css/layout.css');
        //Scripts
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.6.min.js')
            ->prependFile($this->basePath() . '/js/cufon-yui.js')
            ->prependFile($this->basePath() . '/js/cufon-replace.js')
            ->prependFile($this->basePath() . '/js/Open_Sans_400.font.js')
            ->prependFile($this->basePath() . '/js/Open_Sans_Light_300.font.js"')
            ->prependFile($this->basePath() . 'js/Open_Sans_Semibold_600.font.js')
            ->prependFile($this->basePath() . '/js/FF-cash.js');
    ?>
    <!--[if lt IE 7]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/images/upgrade.jpg" border="0"  alt="" /></a>
    </div>
    <![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/html5.js"></script>
    <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen">
    <![endif]-->
</head>
<body id="page2">
<!-- header -->
<div class="bg">
    <div class="main">
        <header>
            <div class="row-1">
                <h1>
                    <a class="logo" href="index.html">Point.co</a>
                    <strong class="slog">The most creative ideas</strong>
                </h1>

            </div>
            <div class="row-2">
                <nav>
                    <ul class="menu">
                        <li><a href="index.html">Home Page</a></li>
                        <li><a class="active" href="news.html">Our News</a></li>
                        <li><a href="services.html">Our Services</a></li>
                        <li><a href="products.html">Our Products</a></li>
                        <li class="last-item"><a href="contacts.html">Contact Us</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <!-- content --><div class="ic">More Website Templates  at TemplateMonster.com!</div>
        <section id="content">
            <div class="padding">
                <div class="wrapper p4">
                    <div class="col-3">
                        <div class="indent">
                            <h2>Latest News</h2>
                           <?php echo $this->content ?>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="block-news">
                            <h3 class="color-4 p2">Archive</h3>
                            <div class="wrapper indent-bot">
                                <ul class="list-2">
                                    <li><a href="#">May 2011</a></li>
                                    <li><a href="#">April 2011</a></li>
                                    <li><a href="#">March 2011</a></li>
                                    <li><a href="#">February 2011</a></li>
                                    <li><a href="#">January 2011</a></li>
                                    <li><a href="#">December 2010</a></li>
                                    <li><a href="#">November 2010</a></li>
                                    <li><a href="#">October 2010</a></li>
                                    <li><a href="#">September 2010</a></li>
                                    <li><a href="#">August 2010</a></li>
                                    <li><a href="#">July 2010</a></li>
                                    <li><a href="#">June 2010</a></li>
                                </ul>
                            </div>
                            <a class="button-2" href="#">Previous Years</a>
                        </div>
                    </div>
                </div>
                <div class="box-bg">
                    <div class="wrapper">


                    </div>
                </div>
            </div>
        </section>
        <!-- footer -->
        <footer>
            <div class="row-top">
                <div class="row-padding">
                    <div class="wrapper">
                        <div class="col-1">
                            <h4>Address:</h4>
                            <dl class="address">
                                <dt><span>Country:</span>USA</dt>
                                <dd><span>City:</span>San Diego</dd>
                                <dd><span>Address:</span>Beach st. 54</dd>
                                <dd><span>Email:</span><a href="#">lcenter@mail.com</a></dd>
                            </dl>
                        </div>
                        <div class="col-2">
                            <h4>Follow Us:</h4>
                            <ul class="list-services">
                                <li class="item-1"><a href="#">Facebook</a></li>
                                <li class="item-2"><a href="#">Twitter</a></li>
                                <li class="item-3"><a href="#">LinkedIn</a></li>
                            </ul>
                        </div>
                        <div class="col-3">
                            <h4>Why Us:</h4>
                            <ul class="list-1">
                                <li><a href="#">Lorem ipsum dolor</a></li>
                                <li><a href="#">Aonsect adipisic</a></li>
                                <li><a href="#">Eiusmjkod tempor</a></li>
                                <li><a href="#">Incididunt ut labore</a></li>
                            </ul>
                        </div>
                        <div class="col-4">
                            <div class="indent3">
                                <strong class="footer-logo">Point.<strong>co</strong></strong>
                                <strong class="phone"><strong>Toll Free:</strong> 1-800-567-8934</strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-bot">
                <div class="aligncenter">
                    <p class="p0"><a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website Template</a> by TemplateMonster.com | <a rel="nofollow" href="http://www.html5xcss3.com/" target="_blank">html5xcss3.com<a/></p>
                    <a href="http://www.templates.com/product/3d-models/" target="_blank">3D Models</a> provided by Templates.com<br>
                    <!-- {%FOOTER_LINK} -->
                </div>
            </div>
        </footer>
    </div>
</div>
<script type="text/javascript"> Cufon.now(); </script>
<?php echo $this->inlineScript() ?>
</body>
</html>
